services:
  rewards-farmer:
    image: ms-rewards-kmeans:5
    container_name: ms-reward-farmer
    shm_size: 8gb
    volumes:
      - ./accounts.json:/app/accounts.json
      - ./tmp:/app/tmp
      - ./logs:/app/logs
    restart: 'no'
  rewards-farmer2:
    image: ms-rewards-kmeans:5
    container_name: ms-reward-farmer2
    shm_size: 8gb
    volumes:
      - ./accounts2.json:/app/accounts.json
      - ./tmp2:/app/tmp
      - ./logs2:/app/logs
    restart: 'no'
  rewards-farmer3:
    image: ms-rewards-kmeans:5
    container_name: ms-reward-farmer3
    shm_size: 8gb
    volumes:
      - ./accounts3.json:/app/accounts.json
      - ./tmp3:/app/tmp
      - ./logs3:/app/logs
    restart: 'no'
  rewards-farmer4:
    image: ms-rewards-kmeans:5
    container_name: ms-reward-farmer4
    shm_size: 8gb
    volumes:
      - ./accounts4.json:/app/accounts.json
      - ./tmp4:/app/tmp
      - ./logs4:/app/logs
    restart: 'no'
