  services:
    rewards-farmer1:
      image: farmer_ms:latest
      container_name: farmer1
      shm_size: 6gb
      command: bash -c 'python3 main.py -v'
      volumes:
        - ./accounts.json:/app/accounts.json
        - ./logs1:/app/logs
      restart: 'no'

    rewards-farmer2:
      image: farmer_ms:latest
      container_name: farmer2
      shm_size: 6gb
      command: bash -c 'python3 main.py -v'
      volumes:
        - ./accounts2.json:/app/accounts.json
        - ./logs2:/app/logs
      restart: 'no'

...
