  services:
    rewards-farmer1:
      image: farmer_ms:latest
      container_name: farmer1
      shm_size: 2gb
      command: bash -c 'python3 main.py <args of bot like (no write -v) -t >'
      volumes:
        - ./accounts.json:/app/accounts.json
        - ./logs1:/app/logs
      restart: 'no'

    rewards-farmer2:
      image: farmer_ms:latest
      container_name: farmer2
      shm_size: 2gb
      command: bash -c 'python3 main.py <args of bot like (no write -v) -t >'
      volumes:
        - ./accounts2.json:/app/accounts.json
        - ./logs2:/app/logs
      restart: 'no'

    rewards-farmer3:
      image: farmer_ms:latest
      container_name: farmer3
      shm_size: 2gb
      command: bash -c 'python3 main.py <args of bot like (no write -v) -t >'
      volumes:
        - ./accounts3.json:/app/accounts.json
        - ./logs3:/app/logs
      restart: 'no'

    rewards-farmer4:
      image: farmer_ms:latest
      container_name: farmer4
      shm_size: 2gb
      command: bash -c 'python3 main.py <args of bot like (no write -v) -t >'
      volumes:
        - ./accounts4.json:/app/accounts.json
        - ./logs4:/app/logs
      restart: 'no'
